[env:heltec-v3]
extends = esp32s3_base
board = heltec_wifi_lora_32_V3
board_check = true
board_build.partitions = default_8MB.csv

lib_deps =
  ${esp32s3_base.lib_deps}
  adafruit/Adafruit MAX1704X@^1.0.3
  td-er/SparkFun MAX1704x Fuel Gauge Arduino Library@^1.0.1

lib_ignore =
  Adafruit MPU6050
  MPU6050
  arduinoFFT

build_flags =
  ${esp32s3_base.build_flags}

  ; your local headers
  -Isrc/modules/treeguard/MPU6050
  -Isrc/modules/treeguard/fft

  ; nanopb (generated protos)
  -Isrc/mesh/generated
  -Isrc/mesh/generated/meshtastic
  -I.pio/libdeps/${PIOENV}/Nanopb/src
  -I.pio/libdeps/${PIOENV}/Nanopb/src/nanopb

  ; variant + toggles
  -Ivariants/heltec_v3
  -D HELTEC_V3
  -D GPS_POWER_TOGGLE
  -D USE_MAX1704X

  ; keep motion off, but DO NOT disable I2C
  -DTG_DISABLE_CORE_MOTION=1
  -DMESHTASTIC_EXCLUDE_MOTION=1
  -DMESHTASTIC_EXCLUDE_MOTION_MODULE=1
  -DMESHTASTIC_EXCLUDE_DETECTIONSENSOR=1
  -DMESHTASTIC_EXCLUDE_SCREEN=1
